version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/aqsa326/Fortress-app"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "ansible"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "vue",
    "react",
    "angularjs",
    "angular"
  ]
  environment = [
    "browser",
    "nodejs",
    "cypress",
    "jest",
    "vitest"
  ]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "php"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "21"
  language_version = "2.1"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "scala"